# Makefile
#
# Targets:
# 	all: Builds the code
# 	build: Builds the code
# 	fmt: Formats the source files
# 	clean: cleans the code
#

# Go parameters
GOCMD=go
GOBUILD=$(GOCMD) build -o $(GOPATH)/$(CURDIR)
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOFMT=gofmt -w

# Package lists
TOPLEVEL_PKG := .

.PHONY: all

all: build
build:
	$(GOBUILD)
clean: 
	$(GOCLEAN)
test: 
	$(GOTEST)
fmt: 
	$(GOFMT)
